apiVersion: v1
kind: Service
metadata:
  name: terminal
  labels:
    app: eumatheia
    component: terminal
spec:
  selector:
    app: eumatheia
    component: terminal
  ports:
    - name: ttyd
      protocol: TCP
      port: 7681
      targetPort: 7681
  type: ClusterIP
